### ISSUE TITLE
POC of Slack-bot based feature to manage access requests

### ISSUE THREAD

**Issue by rchampourlier** [jobteaser/job_tomate#90]
The goal of this feature is to enable team members to request access to applications (e.g. Phraseapp, Mailtrap...) using Slack-bot commands.

### Requirements

- [ ] The bot provides commands the following commands:
  - [ ] `/access request for Confluence`
  - [ ] `/access list available applications`
- [ ] The bot creates a ticket on a dedicated Jira board to track the access requests. It will then update the requests while they are processed (validated / rejected, access processing...).
- [ ] The bot identifies who is able to validate and provide the access and notifies him.her through Slack, asking an answer (validate, decline or escalate).
- [ ] The bot notifies the requester of the status of the request.
- [ ] The bot provides indications to the validator if the request is accepted on how to provide the access.

### Implementation steps

- [ ] Create a dedicated Jira board
- [ ] Restore the Slack bot
- [ ] Add appropriate Slack-bot commands
- [ ] Add a new model for application access (application, validator...)
- [ ] Integrate the new model with the Google Sheets for configuration
- [ ] Implement the different scenarios
